### PR TITLE
[patch] add Init()

### PR DESCRIPTION
**Pull request by WindzCUHK**
TODO:
- [x] block by: https://github.com/yahoojapan/athenz-authorizer/pull/48
- [x] change base and cherry pick
- [x] update go.mod

### CODE REVIEW

**Comment by kevindiu** [comment]
Can we change the base to master and merge it as soon as possible?

**Comment by WindzCUHK** [comment]
what command are you using to cleanup `go.mod`?
I use
``` bash
go get -u -m
go mod tidy
```

**Comment by kevindiu** [comment]
I remove the go.mod and go.sum file and use `go mod vendor` to generate the go mod file.
I think `go mod tidy` will generate platform dependent dependencies so I think my way is better.
Ref: https://github.com/golang/go/wiki/Modules#why-does-go-mod-tidy-record-indirect-and-test-dependencies-in-my-gomod

**Comment by kevindiu** [comment]
Other than go.mod and go.sum file, LGTM

**Comment by WindzCUHK** [comment]
> I remove the go.mod and go.sum file and use `go mod vendor` to generate the go mod file.
> I think `go mod tidy` will generate platform dependent dependencies so I think my way is better.
> Ref: https://github.com/golang/go/wiki/Modules#why-does-go-mod-tidy-record-indirect-and-test-dependencies-in-my-gomod

From the doc,
> go mod tidy also ensures your current go.mod reflects the dependency requirements for all possible combinations of OS, architecture, and build tags
1. It means platform independent? Test result can be reproduced in all platforms.

2. `go mod vendor` just create the `vendor` folder? Seems it is just the same as `go get` for updating the `go.mod` file.
https://github.com/golang/go/wiki/Modules#daily-workflow

**Comment by kevindiu** [comment]
Oh, `It is always good practice to run go mod tidy before committing a go.mod file to version control.`

Ref: https://blog.golang.org/migrating-to-go-modules

**Comment by kevindiu** [comment]
after I use `go mod tidy`, the result is different from yours....

**Comment by kevindiu** [comment]
committed the changes....

**Comment by WindzCUHK** [comment]
which go version are you using?

I got 1 more indirect `github.com/cespare/xxhash/v2 v2.1.0 // indirect`
```
require (
	bou.ke/monkey v1.0.1 // indirect
	github.com/cespare/xxhash/v2 v2.1.0 // indirect
	github.com/kpango/glg v1.4.6
	github.com/kr/pretty v0.1.0 // indirect
	github.com/pkg/errors v0.8.1
	github.com/yahoojapan/athenz-authorizer/v2 v2.1.0
	golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
	gopkg.in/yaml.v2 v2.2.2
)
```
```
$ go mod why github.com/cespare/xxhash/v2
# github.com/cespare/xxhash/v2
github.com/yahoojapan/authorization-proxy/service
github.com/yahoojapan/athenz-authorizer/v2
github.com/kpango/gache
github.com/cespare/xxhash/v2
```

**Comment by kevindiu** [comment]
I deleted the go.mod file and then run the `go mod tidy` command to generate the file... 
I am using the latest version...

**Comment by WindzCUHK** [comment]
It is add by `go get -u`. It will also mark to use latest packages of the indirect dependency...
https://github.com/kpango/gache/blob/6798c0d807b131f43904f6935fac23b936e16f40/go.mod#L10
saver to keep the old version

---

https://github.com/yahoojapan/authorization-proxy/pull/33/commits/fd1ac7ac17e279004f584a739e1b7d0d936984b5, LGTM

**Pull request merged**
