### PR TITLE
Upgrade go.mod

### PR DESCRIPTION
**Pull request by kyfujisa**
upgrade to v2

### CODE REVIEW

**Comment by WindzCUHK** [comment]
need to update the pipeline at the same time like authorizer
https://github.com/yahoojapan/athenz-authorizer/blob/master/.circleci/config.yml#L52

The current pipeline does **NOT** tag with the `v` prefix
https://github.com/yahoojapan/athenz-authorizer/blob/d896d3edec8f0d2abd90d20ff3ffd84abb2e702c/.circleci/config.yml#L52

**Comment by kyfujisa** [comment]
@WindzCUHK 
oh OK.

**Comment by kyfujisa** [comment]
After this fix, I'll put a tag with a v-prefix on it.

**Comment by kyfujisa** [comment]
After this fix, I'll put a tag with a v-prefix on it.

**Comment by kyfujisa** [comment]
I need to include another modification, so I'll close it.

**Pull request closed without merging**
